modLoader="javafml"
loaderVersion="[45,)"
license="All rights reserved"
issueTrackerURL="https://github.com/simon-mc28/Crafting-Mania-Forge/issues"

[[mods]]
modId="craftingmania"
version="1.19.4-1.4.0"
displayName="Crafting Mania"
displayURL="https://curseforge.com/minecraft/mc-mods/crafting-mania"
logoFile="logo.png"
authors="ckmrd1, simon_mc"
description='''
This mod aims to add a craft for all items that haven´t one yet.
'''

[[dependencies.craftingmania]]
    modId="forge"
    mandatory=true
    versionRange="[45,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.craftingmania]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.4,1.20)"
    ordering="NONE"
    side="BOTH"
